# config = {
#     "LR": 2.5e-3,
#     "NUM_ENVS": 1,
#     "NUM_STEPS": 128,
#     "TOTAL_TIMESTEPS": 5e5,
#     "UPDATE_EPOCHS": 2,
#     "NUM_MINIBATCHES": 1,
#     "GAMMA": 0.99,
#     "GAE_LAMBDA": 0.95,
#     "CLIP_EPS": 0.02,
#     "ENT_COEF": 0.001,
#     "VF_COEF": 0.5,
#     "MAX_GRAD_NORM": 0.5,
#     "ACTIVATION": "tanh",
#     "ENV_NAME": "CartPole-v1",
#     "ANNEAL_LR": True,
#     "TRANSITION_MODEL_LR": 1e-4,
#     "SCHEDULE_ACCELERATOR": 1.0,
# }
config = {
    "LR": 5e-4,
    "NUM_ENVS": 64,
    "NUM_STEPS": 128,
    "TOTAL_TIMESTEPS": 1e7,
    "UPDATE_EPOCHS": 4,
    "NUM_MINIBATCHES": 8,
    "GAMMA": 0.999,
    "GAE_LAMBDA": 0.95,
    "CLIP_EPS": 0.2,
    "ENT_COEF": 0.01,
    "VF_COEF": 0.5,
    "MAX_GRAD_NORM": 0.5,
    "ACTIVATION": "relu",
    "ENV_NAME": "Asterix-MinAtar",
    "ANNEAL_LR": True,
    "TRANSITION_MODEL_LR": 1e-4,
    "SCHEDULE_ACCELERATOR": 1.0,
}
