config = {
    "LR": 2.5e-4,
    "NUM_ENVS": 1,
    "NUM_STEPS": 128,
    "TOTAL_TIMESTEPS": 1e5,
    "UPDATE_EPOCHS": 4,
    "NUM_MINIBATCHES": 2,
    "GAMMA": 0.99,
    "GAE_LAMBDA": 0.95,
    "CLIP_EPS": 0.02,
    "ENT_COEF": 0.0001,
    "VF_COEF": 0.5,
    "MAX_GRAD_NORM": 0.5,
    "ACTIVATION": "tanh",
    "ENV_NAME": "CartPole-v1",
    "ANNEAL_LR": True,
    "TRANSITION_MODEL_LR": 1e-4,
    "SCHEDULE_ACCELERATOR": 1.0,
}
